"""
Query executor for MongoDB operations.

This module provides a higher-level interface for executing MongoDB queries
generated by the AI agent. It handles query validation, execution, and
result formatting.

Author: AI Agent Development Team
"""

import json
from typing import Any, Dict, List, Optional

from mongodb_agent.database.mongodb_client import MongoDBClient
from mongodb_agent.utils.formatting import format_mongodb_result, format_query_for_display
from mongodb_agent.utils.logger import get_logger

logger = get_logger(__name__)


class QueryExecutor:
    """
    High-level query executor for MongoDB operations.

    This class wraps MongoDBClient and provides:
    - Query validation
    - Safe query execution
    - Result formatting
    - Error handling with user-friendly messages

    Example usage:
        >>> executor = QueryExecutor()
        >>> result = executor.execute_query(
        ...     query_type="find",
        ...     collection="movies",
        ...     query={"year": 2020}
        ... )
        >>> print(result["formatted_result"])
    """

    def __init__(self, mongodb_client: Optional[MongoDBClient] = None):
        """
        Initialize query executor.

        Args:
            mongodb_client: MongoDB client instance. If None, creates new one.
        """
        self.client = mongodb_client or MongoDBClient()
        logger.info("QueryExecutor initialized")

    def execute_query(
        self,
        query_type: str,
        collection: str,
        query: Dict[str, Any] | List[Dict[str, Any]],
        limit: int = 100,
    ) -> Dict[str, Any]:
        """
        Execute MongoDB query and return formatted results.

        Args:
            query_type: Type of query ("find" or "aggregate")
            collection: Collection name
            query: Query document (for find) or pipeline (for aggregate)
            limit: Maximum number of results to return

        Returns:
            Dictionary containing:
            - success: Whether query succeeded
            - results: Raw query results
            - formatted_result: User-friendly formatted results
            - query_display: Formatted query for display
            - error: Error message (if failed)

        Example:
            >>> result = executor.execute_query(
            ...     query_type="aggregate",
            ...     collection="movies",
            ...     query=[
            ...         {"$match": {"year": {"$gte": 2020}}},
            ...         {"$group": {"_id": "$year", "count": {"$sum": 1}}}
            ...     ]
            ... )
            >>> if result["success"]:
            ...     print(result["formatted_result"])
        """
        try:
            logger.info(
                f"Executing {query_type} query",
                extra={"collection": collection, "query_type": query_type},
            )

            # Validate inputs
            self._validate_query(query_type, collection, query)

            # Execute query based on type
            if query_type == "find":
                results = self._execute_find(collection, query, limit)
            elif query_type == "aggregate":
                results = self._execute_aggregate(collection, query)
            else:
                raise ValueError(f"Unsupported query type: {query_type}")

            # Format results
            formatted_result = format_mongodb_result(results, limit=limit)
            query_display = format_query_for_display(query_type, query, collection)

            logger.info(
                f"Query executed successfully",
                extra={"result_count": len(results), "query_type": query_type},
            )

            return {
                "success": True,
                "results": results,
                "formatted_result": formatted_result,
                "query_display": query_display,
                "result_count": len(results),
            }

        except Exception as e:
            logger.error(f"Query execution failed: {e}", exc_info=True)

            return {
                "success": False,
                "results": [],
                "formatted_result": f"Query execution failed: {str(e)}",
                "query_display": format_query_for_display(query_type, query, collection),
                "error": str(e),
                "result_count": 0,
            }

    def _validate_query(
        self,
        query_type: str,
        collection: str,
        query: Dict[str, Any] | List[Dict[str, Any]],
    ) -> None:
        """
        Validate query parameters.

        Args:
            query_type: Type of query
            collection: Collection name
            query: Query document or pipeline

        Raises:
            ValueError: If validation fails
        """
        if not collection or not isinstance(collection, str):
            raise ValueError("Collection name must be a non-empty string")

        if query_type not in ["find", "aggregate"]:
            raise ValueError(f"Invalid query type: {query_type}. Must be 'find' or 'aggregate'")

        if query_type == "find" and not isinstance(query, dict):
            raise ValueError("Find query must be a dictionary")

        if query_type == "aggregate" and not isinstance(query, list):
            raise ValueError("Aggregate query must be a list of pipeline stages")

    def _execute_find(
        self, collection: str, query: Dict[str, Any], limit: int
    ) -> List[Dict[str, Any]]:
        """
        Execute find query.

        Args:
            collection: Collection name
            query: Find query document
            limit: Result limit

        Returns:
            List of documents
        """
        # Create a copy to avoid mutating the original query
        query_copy = dict(query)

        # Extract projection if present (use get to avoid mutation)
        projection = query_copy.pop("projection", None)

        # Extract sort if present
        sort_spec = query_copy.pop("sort", None)

        # Convert sort dict to list of tuples if needed
        sort = None
        if sort_spec:
            if isinstance(sort_spec, dict):
                sort = list(sort_spec.items())
            elif isinstance(sort_spec, list):
                sort = sort_spec

        return self.client.find(
            collection=collection,
            filter_dict=query_copy,
            projection=projection,
            limit=limit,
            sort=sort,
        )

    def _execute_aggregate(
        self, collection: str, pipeline: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Execute aggregation pipeline.

        Args:
            collection: Collection name
            pipeline: Aggregation pipeline

        Returns:
            List of aggregation results
        """
        return self.client.aggregate(collection=collection, pipeline=pipeline)

    def get_schema(self, collection: str) -> Dict[str, Any]:
        """
        Get schema information for collection.

        Args:
            collection: Collection name

        Returns:
            Schema information dictionary
        """
        return self.client.get_collection_schema(collection)

    def close(self) -> None:
        """Close database connection."""
        self.client.close()

    def __enter__(self) -> "QueryExecutor":
        """Context manager entry."""
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit."""
        self.close()
